version: '3.9'

services:
  db:
    image: mariadb:10.2.6
    ports:
      - "8301:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: testdb
      MYSQL_PASSWORD: testdb
    networks:
      - db
    volumes:
      - ./dbscript/init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    networks:
      - php
  php-fpm:
    build: ./php-fpm
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:
      - db
      - php

networks:
  db:
  php: